/** Auto-generated by scripts/setup-exam-audio.mjs — do not edit manually */
import type { ExamVersion } from "@/lib/exams/types";

export const EXAM_AUDIO_FOLDERS: Record<ExamVersion, string> = {
  "23C": "Prova 23C",
  "24C": "Prova 24C",
  "25C": "Prova 25C",
  "26C": "Prova 26C"
} as const;

/** Track number (1–14) → original filename in provas folder */
export const EXAM_AUDIO_FILES: Record<ExamVersion, Record<number, string>> = {
  "23C": {
    "1": "Track1.mp3",
    "2": "Track2.mp3",
    "3": "Track3.mp3",
    "4": "Track4.mp3",
    "5": "Track5.mp3",
    "6": "Track6.mp3",
    "7": "Track7.mp3",
    "8": "Track8.mp3",
    "9": "Track9.mp3",
    "10": "Track10.mp3",
    "11": "Track11.mp3",
    "12": "Track12.mp3",
    "13": "Track13.mp3",
    "14": "Track14.mp3"
  },
  "24C": {
    "1": "AUDIO-2026-04-10-09-46-56.mp3",
    "2": "AUDIO-2026-04-10-09-46-57.mp3",
    "3": "AUDIO-2026-04-10-09-46-57 2.mp3",
    "4": "AUDIO-2026-04-10-09-46-57 3.mp3",
    "5": "AUDIO-2026-04-10-09-46-58.mp3",
    "6": "AUDIO-2026-04-10-09-46-58 2.mp3",
    "7": "AUDIO-2026-04-10-09-46-58 3.mp3",
    "8": "AUDIO-2026-04-10-09-46-58 4.mp3",
    "9": "AUDIO-2026-04-10-09-46-59.mp3",
    "10": "AUDIO-2026-04-10-09-46-59 2.mp3",
    "11": "AUDIO-2026-04-10-09-46-59 3.mp3",
    "12": "AUDIO-2026-04-10-09-47-00.mp3",
    "13": "AUDIO-2026-04-10-09-47-00 2.mp3",
    "14": "AUDIO-2026-04-10-09-47-00 3.mp3"
  },
  "25C": {
    "1": "AUDIO-2026-04-10-09-46-52.mp3",
    "2": "AUDIO-2026-04-10-09-46-52 2.mp3",
    "3": "AUDIO-2026-04-10-09-46-53.mp3",
    "4": "AUDIO-2026-04-10-09-46-53 2.mp3",
    "5": "AUDIO-2026-04-10-09-46-53 3.mp3",
    "6": "AUDIO-2026-04-10-09-46-54.mp3",
    "7": "AUDIO-2026-04-10-09-46-54 2.mp3",
    "8": "AUDIO-2026-04-10-09-46-54 3.mp3",
    "9": "AUDIO-2026-04-10-09-46-54 4.mp3",
    "10": "AUDIO-2026-04-10-09-46-55.mp3",
    "11": "AUDIO-2026-04-10-09-46-55 2.mp3",
    "12": "AUDIO-2026-04-10-09-46-55 3.mp3",
    "13": "AUDIO-2026-04-10-09-46-56.mp3",
    "14": "AUDIO-2026-04-10-09-46-56 2.mp3"
  },
  "26C": {
    "1": "AUDIO-2026-04-10-09-46-48.mp3",
    "2": "AUDIO-2026-04-10-09-46-48 2.mp3",
    "3": "AUDIO-2026-04-10-09-46-49.mp3",
    "4": "AUDIO-2026-04-10-09-46-49 2.mp3",
    "5": "AUDIO-2026-04-10-09-46-49 3.mp3",
    "6": "AUDIO-2026-04-10-09-46-49 4.mp3",
    "7": "AUDIO-2026-04-10-09-46-50.mp3",
    "8": "AUDIO-2026-04-10-09-46-50 2.mp3",
    "9": "AUDIO-2026-04-10-09-46-50 3.mp3",
    "10": "AUDIO-2026-04-10-09-46-50 4.mp3",
    "11": "AUDIO-2026-04-10-09-46-51.mp3",
    "12": "AUDIO-2026-04-10-09-46-51 2.mp3",
    "13": "AUDIO-2026-04-10-09-46-51 3.mp3",
    "14": "AUDIO-2026-04-10-09-46-52.mp3"
  }
} as const;

export const SOUND_CHECK_TRACK = 1;
