/** Auto-generated from knowledge/drafts/batch-01 — run: node scripts/generate-dev-knowledge-entries.mjs */
import type { DevKnowledgeEntry } from "@/lib/knowledge/devKnowledge/types";

export const BATCH01_DEV_ENTRIES: DevKnowledgeEntry[] = [
  {
    "catalogId": "0001",
    "id": "dev-0001",
    "term": "fly direct",
    "slug": "fly-direct",
    "category": "ATC Phraseology",
    "meaningEn": "Fly straight to a specified waypoint, fix, or navigation aid.",
    "meaningPt": "Voar direto para um ponto.",
    "whenUsed": "ATC uses this to shorten the route, simplify navigation, or reposition traffic. FAA defines “direct” as straight-line flight between navigation aids, fixes, or points. The pilot must read back the point and navigate directly to it while complying with the rest of the clearance.",
    "example": "Helicopter PT-ABC, fly direct NITUX.",
    "sayPhrase": "Flying direct NITUX, PT-ABC.",
    "icaoQuestion": "When would ATC ask a pilot to fly direct?",
    "icaoSpeakText": "Cleared direct AFA VOR, PT-ABC."
  },
  {
    "catalogId": "0002",
    "id": "dev-0002",
    "term": "hold short",
    "slug": "hold-short",
    "category": "ATC Phraseology",
    "meaningEn": "Stop before a runway, taxiway, or specified point and do not cross it.",
    "meaningPt": "Manter-se antes do ponto indicado / não cruzar.",
    "whenUsed": "Used mainly on the ground to prevent runway incursions and protect active runways or movement areas. Hold short is a safety-critical instruction — the pilot must read it back in full and stop at the holding point. Never assume a taxi clearance allows runway crossing unless the clearance explicitly includes it.",
    "example": "PT-ABC, hold short of runway one eight.",
    "sayPhrase": "Holding short runway one eight, PT-ABC.",
    "icaoQuestion": "Why is it important to read back hold short instructions correctly?",
    "icaoSpeakText": "Taxi via Alpha, holding short runway two seven, PT-ABC."
  },
  {
    "catalogId": "0003",
    "id": "dev-0003",
    "term": "line up and wait",
    "slug": "line-up-and-wait",
    "category": "ATC Phraseology",
    "meaningEn": "Enter the departure runway, align with the runway, and wait for takeoff clearance.",
    "meaningPt": "Alinhar na pista e aguardar.",
    "whenUsed": "ATC uses it when the aircraft may enter the runway, but takeoff clearance cannot be issued yet. You are on the runway but not cleared for takeoff — position for imminent departure while landing traffic clears or wake turbulence dissipates.",
    "example": "PT-ABC, line up and wait runway one eight.",
    "sayPhrase": "Line up and wait runway one eight, PT-ABC.",
    "icaoQuestion": "What is the difference between line up and wait and cleared for takeoff?",
    "icaoSpeakText": "Runway two seven, lining up and waiting, PT-ABC."
  },
  {
    "catalogId": "0004",
    "id": "dev-0004",
    "term": "cleared for takeoff",
    "slug": "cleared-for-takeoff",
    "category": "ATC Phraseology",
    "meaningEn": "ATC authorizes the aircraft to begin the takeoff roll.",
    "meaningPt": "Autorizado para decolagem.",
    "whenUsed": "This is the explicit clearance required before an aircraft may take off from a controlled runway. It follows line up and wait when applicable — the pilot must not enter the takeoff roll until this clearance is clearly received and read back.",
    "example": "PT-ABC, runway one eight, cleared for takeoff.",
    "sayPhrase": "Runway one eight, cleared for takeoff, PT-ABC.",
    "icaoQuestion": "Why is it dangerous to confuse line up and wait with cleared for takeoff?",
    "icaoSpeakText": "Cleared for takeoff runway two seven, PT-ABC."
  },
  {
    "catalogId": "0005",
    "id": "dev-0005",
    "term": "cleared to land",
    "slug": "cleared-to-land",
    "category": "ATC Phraseology",
    "meaningEn": "ATC authorizes the aircraft to land on the specified runway or landing area.",
    "meaningPt": "Autorizado para pouso.",
    "whenUsed": "Issued by Tower when the runway or landing area is available and landing is authorized. Continue approach is not the same as cleared to land — the pilot should wait for an explicit landing clearance before landing at a controlled airport.",
    "example": "PT-ABC, runway one eight, cleared to land.",
    "sayPhrase": "Runway one eight, cleared to land, PT-ABC.",
    "icaoQuestion": "What should a pilot do if he is on final but has not received landing clearance?",
    "icaoSpeakText": "Cleared to land runway two seven, PT-ABC."
  },
  {
    "catalogId": "0006",
    "id": "dev-0006",
    "term": "continue approach",
    "slug": "continue-approach",
    "category": "Approach",
    "meaningEn": "Continue flying the published or instructed approach. Landing clearance has not yet been issued.",
    "meaningPt": "Continue a aproximação.",
    "whenUsed": "Tower issues this instruction when the runway is not yet available but expects to clear the aircraft to land later. The aircraft continues the approach while awaiting further instructions. Continue approach does not authorize landing.",
    "example": "PT-ABC, continue approach.",
    "sayPhrase": "Continuing approach, PT-ABC.",
    "icaoQuestion": "What is the difference between continue approach and cleared to land?",
    "icaoSpeakText": "Continue approach, number two, PT-ABC."
  },
  {
    "catalogId": "0007",
    "id": "dev-0007",
    "term": "go around",
    "slug": "go-around",
    "category": "Approach",
    "meaningEn": "Discontinue the landing and climb away for another approach.",
    "meaningPt": "Arremeter.",
    "whenUsed": "Used whenever landing is no longer safe. It may be instructed by ATC or initiated by the pilot. A go around is never considered a failure — professional pilots initiate one whenever the approach becomes unstable or safety margins are reduced.",
    "example": "PT-ABC, go around.",
    "sayPhrase": "Going around, PT-ABC.",
    "icaoQuestion": "When would you decide to perform a go around?",
    "icaoSpeakText": "Go around acknowledged, PT-ABC."
  },
  {
    "catalogId": "0008",
    "id": "dev-0008",
    "term": "missed approach",
    "slug": "missed-approach",
    "category": "Instrument Procedures",
    "meaningEn": "A published IFR procedure followed when the required visual references are not obtained or landing cannot be completed.",
    "meaningPt": "Procedimento de aproximação perdida.",
    "whenUsed": "Every instrument approach includes a missed approach procedure. It protects terrain clearance and separates aircraft. A missed approach is a published IFR procedure; a go around is simply discontinuing the landing — sometimes both happen together.",
    "example": "PT-ABC, execute published missed approach.",
    "sayPhrase": "Executing published missed approach.",
    "icaoQuestion": "What is the difference between a go around and a missed approach?",
    "icaoSpeakText": "Runway heading, climb three thousand."
  },
  {
    "catalogId": "0009",
    "id": "dev-0009",
    "term": "visual approach",
    "slug": "visual-approach",
    "category": "Approach",
    "meaningEn": "An ATC-authorized approach conducted with visual reference to the airport or preceding aircraft.",
    "meaningPt": "Aproximação visual.",
    "whenUsed": "Used when weather conditions permit visual navigation instead of flying the complete instrument procedure. A visual approach still requires ATC clearance — seeing the runway or airport alone does not authorize landing.",
    "example": "PT-ABC, cleared visual approach runway one eight.",
    "sayPhrase": "Cleared visual approach runway one eight.",
    "icaoQuestion": "Under what conditions may ATC clear an aircraft for a visual approach?",
    "icaoSpeakText": "Airport in sight."
  },
  {
    "catalogId": "0010",
    "id": "dev-0010",
    "term": "radar vectors",
    "slug": "radar-vectors",
    "category": "Navigation",
    "meaningEn": "ATC headings issued to guide an aircraft toward a route, approach, or traffic sequence.",
    "meaningPt": "Vetoração radar.",
    "whenUsed": "Instead of navigating independently, the pilot follows ATC headings until instructed otherwise. While receiving radar vectors, ATC is responsible for navigation guidance. The pilot flies assigned headings until instructed to resume own navigation.",
    "example": "PT-ABC, turn left heading 270.",
    "sayPhrase": "Left heading 270.",
    "icaoQuestion": "Why does ATC provide radar vectors?",
    "icaoSpeakText": "Heading 180."
  }
];
