/** Auto-generated from knowledge/premium — run: node scripts/generate-dev-knowledge-entries.mjs */
import type { DevKnowledgeEntry } from "@/lib/knowledge/devKnowledge/types";

export const BATCH01_DEV_ENTRIES: DevKnowledgeEntry[] = [
  {
    "catalogId": "0001",
    "id": "0001",
    "displayTerm": "Fly Direct",
    "term": "fly direct",
    "slug": "fly-direct",
    "category": "ATC Phraseology",
    "meaningEn": "Fly directly toward a specified waypoint, navigation aid, airport, or fix.",
    "meaningPt": "Voe diretamente para um ponto específico.",
    "whenUsed": "A Fly Direct clearance changes your navigation.",
    "example": "PT-ABC, fly direct NITUX.",
    "sayPhrase": "Flying direct NITUX, PT-ABC.",
    "icaoQuestion": "When would ATC instruct an aircraft to fly direct?",
    "icaoSpeakText": "Cleared direct AFA VOR, PT-ABC."
  },
  {
    "catalogId": "0002",
    "id": "0002",
    "displayTerm": "Hold Short",
    "term": "hold short",
    "slug": "hold-short",
    "category": "ATC Phraseology",
    "meaningEn": "Stop before a runway, taxiway, or designated holding position.",
    "meaningPt": "Pare antes da pista ou do ponto de espera indicado.",
    "whenUsed": "A Hold Short instruction requires the aircraft to stop before reaching a runway, taxiway, or any specified holding point.",
    "example": "PT-ABC, hold short runway one eight.",
    "sayPhrase": "Holding short runway one eight, PT-ABC.",
    "icaoQuestion": "Why is it important to read back Hold Short instructions?",
    "icaoSpeakText": "Taxi via Alpha, holding short runway two seven, PT-ABC."
  },
  {
    "catalogId": "0003",
    "id": "0003",
    "displayTerm": "Line Up and Wait",
    "term": "line up and wait",
    "slug": "line-up-and-wait",
    "category": "ATC Phraseology",
    "meaningEn": "Enter the runway, align the aircraft with the runway centerline, and wait for takeoff clearance.",
    "meaningPt": "Alinhe na pista e aguarde autorização para decolar.",
    "whenUsed": "A Line Up and Wait (LUAW) clearance authorizes the aircraft to enter the active runway and position itself for departure.",
    "example": "PT-ABC, runway one eight, line up and wait.",
    "sayPhrase": "Line up and wait runway one eight, PT-ABC.",
    "icaoQuestion": "What is the difference between \"Line Up and Wait\" and \"Cleared for Takeoff\"?",
    "icaoSpeakText": "Lining up and waiting runway two seven, PT-ABC."
  },
  {
    "catalogId": "0004",
    "id": "0004",
    "displayTerm": "Cleared for Takeoff",
    "term": "cleared for takeoff",
    "slug": "cleared-for-takeoff",
    "category": "ATC Phraseology",
    "meaningEn": "ATC authorizes the aircraft to begin the takeoff roll on the assigned runway.",
    "meaningPt": "Autorizado para decolagem.",
    "whenUsed": "A Cleared for Takeoff clearance gives the pilot legal and operational authorization to begin the takeoff.",
    "example": "PT-ABC, runway zero seven, cleared for takeoff.",
    "sayPhrase": "Runway zero seven, cleared for takeoff, PT-ABC.",
    "icaoQuestion": "Why is it dangerous to assume you are cleared for takeoff?",
    "icaoSpeakText": "Cleared for takeoff runway one eight, PT-ABC."
  },
  {
    "catalogId": "0005",
    "id": "0005",
    "displayTerm": "Cleared to Land",
    "term": "cleared to land",
    "slug": "cleared-to-land",
    "category": "ATC Phraseology",
    "meaningEn": "ATC authorizes the aircraft to land on the specified runway.",
    "meaningPt": "Autorizado para pouso.",
    "whenUsed": "A Cleared to Land clearance authorizes the pilot to complete the landing on the assigned runway.",
    "example": "PT-ABC, runway zero seven, cleared to land.",
    "sayPhrase": "Runway zero seven, cleared to land, PT-ABC.",
    "icaoQuestion": "What should a pilot do if the runway is in sight but landing clearance has not been received?",
    "icaoSpeakText": "Cleared to land runway one eight, PT-ABC."
  },
  {
    "catalogId": "0006",
    "id": "0006",
    "displayTerm": "Continue Approach",
    "term": "continue approach",
    "slug": "continue-approach",
    "category": "ATC Phraseology",
    "meaningEn": "Continue flying the approach toward the runway while awaiting further instructions.",
    "meaningPt": "Continue a aproximação.",
    "whenUsed": "A Continue Approach instruction tells the pilot to keep flying the current approach.",
    "example": "PT-ABC, continue approach.",
    "sayPhrase": "Continuing approach, PT-ABC.",
    "icaoQuestion": "What is the difference between Continue Approach and Cleared to Land?",
    "icaoSpeakText": "Continuing approach, number two, PT-ABC."
  },
  {
    "catalogId": "0007",
    "id": "0007",
    "displayTerm": "Go Around",
    "term": "go around",
    "slug": "go-around",
    "category": "ATC Phraseology",
    "meaningEn": "A Go Around is the decision or instruction to discontinue the landing and climb away for another approach.",
    "meaningPt": "Arremeter.",
    "whenUsed": "A Go Around may be:",
    "example": "PT-ABC, Go Around.",
    "sayPhrase": "Going around, PT-ABC.",
    "icaoQuestion": "When would you decide to perform a Go Around?",
    "icaoSpeakText": "PT-ABC going around."
  },
  {
    "catalogId": "0008",
    "id": "0008",
    "displayTerm": "Missed Approach",
    "term": "missed approach",
    "slug": "missed-approach",
    "category": "ATC Phraseology",
    "meaningEn": "A Missed Approach is the published or assigned procedure followed when an aircraft cannot complete an instrument approach and landing.",
    "meaningPt": "Procedimento de aproximação perdida.",
    "whenUsed": "Every IFR approach includes a Missed Approach Procedure (MAP).",
    "example": "ANAC123, execute published missed approach.",
    "sayPhrase": "Executing published missed approach, ANAC123.",
    "icaoQuestion": "What is the difference between a Go Around and a Missed Approach?",
    "icaoSpeakText": "Runway heading, climb three thousand, ANAC123."
  },
  {
    "catalogId": "0009",
    "id": "0009",
    "displayTerm": "Visual Approach",
    "term": "visual approach",
    "slug": "visual-approach",
    "category": "ATC Phraseology",
    "meaningEn": "A Visual Approach is an ATC-authorized approach conducted with visual reference to the airport or the preceding aircraft while remaining under ATC control.",
    "meaningPt": "Aproximação visual.",
    "whenUsed": "A Visual Approach allows the pilot to complete the approach using visual references instead of flying every segment of the published instrument procedure.",
    "example": "Approach: ANAC123, report airport in sight.",
    "sayPhrase": "Airport in sight, ANAC123.",
    "icaoQuestion": "When may ATC clear an aircraft for a Visual Approach?",
    "icaoSpeakText": "Cleared visual approach runway one four, ANAC123."
  },
  {
    "catalogId": "0010",
    "id": "0010",
    "displayTerm": "Radar Vectors",
    "term": "radar vectors",
    "slug": "radar-vectors",
    "category": "Navigation",
    "meaningEn": "Radar Vectors are navigational instructions issued by Air Traffic Control, usually in the form of magnetic headings, to guide an aircraft toward a specific route, approach, or destination.",
    "meaningPt": "Vetoração radar.",
    "whenUsed": "When an aircraft is under Radar Vectors, ATC temporarily assumes responsibility for lateral navigation.",
    "example": "Approach: ANAC123, fly heading zero niner zero.",
    "sayPhrase": "Heading zero niner zero, ANAC123.",
    "icaoQuestion": "Why would ATC provide radar vectors to an aircraft?",
    "icaoSpeakText": "Left heading zero six zero, ANAC123."
  },
  {
    "catalogId": "0011",
    "id": "0011",
    "displayTerm": "Resume Own Navigation",
    "term": "resume own navigation",
    "slug": "resume-own-navigation",
    "category": "Navigation",
    "meaningEn": "Resume Own Navigation instructs the pilot to stop following ATC vectors and continue navigating according to the flight plan, cleared route, or published procedure.",
    "meaningPt": "Retome sua própria navegação.",
    "whenUsed": "When ATC says Resume Own Navigation, the aircraft is no longer being radar vectored.",
    "example": "Approach: ANAC123, resume own navigation.",
    "sayPhrase": "Resuming own navigation, ANAC123.",
    "icaoQuestion": "When would ATC instruct an aircraft to resume own navigation?",
    "icaoSpeakText": "Direct REKPA, resuming own navigation, ANAC123."
  }
];
